# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 27 Jul 2015 20:37:17 +0000
*               @ALL          1
*               @user         8
