<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Mon, 27 Jul 2015 20:37:17 +0000
 */
$conf['title'] = 'Реклама в Новом Уренгое';
$conf['lang'] = 'ru';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
