<?php
/*
 * Local plugin enable/disable settings
 *
 * Auto-generated by install script
 * Date: Mon, 27 Jul 2015 20:37:17 +0000
 */

$plugins['authad']    = 0;
$plugins['authldap']  = 0;
$plugins['authmysql'] = 0;
$plugins['authpgsql'] = 0;
